# delay in ticks before a player can ungrapple
ungrapple-delay: 3

# the rate at which the grappling tether is retracted
retraction-speed: 0.4

# the maximum length a grapple tether can be
max-tether-length: 32

# the minimum length a grapple tether can be
min-tether-length: 4

# how much the tether "stretches" while retracting
tether-stretchiness: 1.1

# particles used to display the tether
particle-options:
    red: 0.8
    green: 0.8
    blue: 0.8
    size: 0.6
    step: 0.4
