name: GrappleHook
version: 0.1
api-version: 1.16
main: lagpickle.grapplehook.GrappleHook
commands:
    grapplehook-reload:
        description: reload plugin config
        permission: grapplehook.reload
    grapplehook-give:
        description: turns item in main hand into a grapple
        permission: grapplehook.give
        usage: /<command> [<player>]
permissions:
    grapplehook.reload:
        default: op
    grapplehook.give:
        default: op
