name: GrappleHook
version: 0.1
api-version: 1.16
main: lagpickle.grapplehook.GrappleHook
commands:
    grapplehook-reload:
        description: reload plugin config
        permission: grapplehook.reload
permissions:
    grapplehook.reload:
        default: op
